# Generated by Django 5.2.7 on 2025-11-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_make_slug_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
